wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.7.7
    cli_version: 0.15.4
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1689431284.647579
    t:
      1:
      - 5
      - 53
      - 55
      3:
      - 13
      - 23
      4: 3.7.7
      5: 0.15.4
      8:
      - 3
      - 5
